version: 0.0
environment_variables:
    plaintext:
        "INPUT_FILE": "saml.yaml"
        "S3_BUCKET": "nht-b2"
containers:
    LambdaFunctions:
        phases:
            during_build:
                commands:
                    - npm install
                    - aws cloudformation package --template $INPUT_FILE --s3-bucket $S3_BUCKET --output-template post-saml.yaml
                    - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
        artifacts:
            files:
                - post-saml.yaml
                - beta.json
                - version.out
